### ISSUE TITLE
Language sample needs to be filled in with a working implementation

### ISSUE THREAD

**Issue by hodgesrm** [microservice-tools/pixis#21]
It's currently difficult to add a new language or framework implementation using the sample implementation in samples/mylang-myimpl-myserver.  Running `pixis -b build.py` in that directory results in the following error:
```
$ pixis -b build.py
build.py
build /home/rhodges/git/pixis/samples/mylang-myimpl-server/build.py
Traceback (most recent call last):
  File "/home/rhodges/git/pixis/pixis-env/bin/pixis", line 10, in <module>
    sys.exit(main())
  File "/home/rhodges/git/pixis/pixis/main.py", line 35, in main
    utils.load_build_file(args.build_file)  # get target implementation/language
  File "/home/rhodges/git/pixis/pixis/utils.py", line 84, in load_build_file
    spec.loader.exec_module(build_script)
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/rhodges/git/pixis/samples/mylang-myimpl-server/build.py", line 5, in <module>
    IMPLEMENTATION = MyImplementation
NameError: name 'MyImplementation' is not defined
```
This is easy to fix because the reference to MyImplementation precedes use.  More generally the example should demonstrate how to define the language and framework fully within build.py (or the directory).  This includes addressing the following issues:

1.) Documented examples of required functions and methods in Implementation class.  

2.) Show how to refer to variables in configuration.  I had problems getting the following type of statement to compile.  MODEL_PACKAGE is a variable I would like to add to the configuration for this Implementation but it's not clear how to do that correctly within build.py.  I actually wanted to read the variable from the config e.g., `cfg.Config.MODEL_PACKAGE` but this can't work because the value has not been set. 
```
    @staticmethod
    def generate_per_schema():
       tmpl.emit_template('server_java_jax_rs/model.j2',
                          os.path.join(
                                       cfg.Config.PATH_OUT,
                                       Java.package_to_path(MODEL_PACKAGE)),
                          tmpl.TEMPLATE_CONTEXT['_current_tag'] + '.java')
```

3.) How to find templates.  Setting TEMPLATES in build.py does not seem to work.  Pixis fails with errors like the following.  It's not clear how the path should work.
```
$ pixis -b build.py -v
build.py
build /home/rhodges/git/pixis/samples/java-jax-rs-server/build.py
/home/rhodges/git/pixis/samples/java-jax-rs-server/swagger.yaml
specification is valid
build /home/rhodges/git/pixis/samples/java-jax-rs-server/build.py
Traceback (most recent call last):
  File "/home/rhodges/git/pixis/pixis/template_handler.py", line 32, in emit_template
    template = env.get_template(template_name)  # template_path is something like: server_flask/model.j2, so we have to do a name comparison here
  File "/home/rhodges/git/pixis/pixis-env/lib/python3.5/site-packages/Jinja2-2.10-py3.5.egg/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/rhodges/git/pixis/pixis-env/lib/python3.5/site-packages/Jinja2-2.10-py3.5.egg/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/rhodges/git/pixis/pixis-env/lib/python3.5/site-packages/Jinja2-2.10-py3.5.egg/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/rhodges/git/pixis/pixis-env/lib/python3.5/site-packages/Jinja2-2.10-py3.5.egg/jinja2/loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: model.j2
```
[build.py.txt](https://github.com/microservice-tools/pixis/files/1997708/build.py.txt)

**Comment by hodgesrm** [comment]
p.s., As a workaround I'm going to add my new language and framework implementation directly to the pixis module.
