### ISSUE TITLE
Pixis command should display help when it cannot find build.py

### ISSUE THREAD

**Issue by hodgesrm** [microservice-tools/pixis#7]
If you type 'pixis' without a build.py in the current directory, pixis responds with a stack trace.  It should instead print a short message saying that a build.py file is required and indicating how to get more help.  (Or just print everything.)
```
$ pixis
['/home/rhodges/environment/rhodges-pixis/bin/pixis']
swagger.yaml
/home/rhodges/git/rhodges-pixis/swagger.yaml
Traceback (most recent call last):
  File "/home/rhodges/environment/rhodges-pixis/bin/pixis", line 10, in <module>
    sys.exit(main())
  File "/home/rhodges/git/rhodges-pixis/pixis/main.py", line 33, in main
    cfg.SPEC_DICT = load_spec_file(cfg.SPEC_FILE_PATH)
  File "/home/rhodges/git/rhodges-pixis/pixis/main.py", line 44, in load_spec_file
    with open(file_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/rhodges/git/rhodges-pixis/swagger.yaml'
```

**Comment by andrew-ni** [comment]
Thanks Robert, I think this got messed up when we refactored the build file/command line process.
